spring:
  application:
    name: airbnb
  config:
    import:
      - app_settings/dev-db-config.yml
      - app_settings/oauth-config.yml
      - app_settings/jwt-config.yml

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /api-ui.html
  api-docs:
    path: /docs
  default-produces-media-type: application/json