spring:
  application:
    name: airbnb
  config:
    import:
      - app_settings/dev-db-config.yml
      - app_settings/oauth-config.yml
      - app_settings/jwt-config.yml

server:
  forward-headers-strategy: FRAMEWORK

logging:
  level:
    com:
      zaxxer:
        hikari: error

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /docs
  api-docs:
    path: /bnb
  default-produces-media-type: application/json