name: CI/CD Front Pipeline

on:
  push:
    branches:
      - Frontend

concurrency:
  group: squdbnb-front-prod
  cancel-in-progress: true

jobs:
  front-build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        cd ${{ github.workspace }}/FE
        npm install

    - name: Build project
      run: |
        cd ${{ github.workspace }}/FE
        npm run build

    - name: Build Docker image
      run: |
        cd ${{ github.workspace }}/FE
        docker build -t kimjooyoung/squadbnb-prod-front:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        cd ${{ github.workspace }}/FE
        docker push kimjooyoung/squadbnb-prod-front:latest

    - name: Deploy to Prod Server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST_PROD }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /home/ubuntu/deploy
          sudo ./deploy.sh


          